
- name: multifile creation in allservers playbook
  hosts: allservers
  tasks:
    - name: multiple file creation using list
      file:
        path: "/tmp/{{item}}"
        state: touch
      with_items:
        - t1.txt
        - t2.txt
        - t3.txt